language: python
python:
  - "2.7"
  - "3.4"
  - "3.3"
# command to install dependencies
env:
  - DJANGO=django==1.6
  - DJANGO=django==1.7
  - DJANGO=django==1.8
install:
  - pip install pytest-django
# command to run tests
script: "py.test ."

branches:
  only:
    - master
	- develop
